spring:
  datasource:
    url: jdbc:h2:file:./data/pikilanddb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:dummy-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:dummy-client-secret}
            scope:
              - read:user
              - repo
